version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db  # webサービスがdbサービスを依存するように指定
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydatabase"  # dbサービスに接続するための設定

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
