services:
  - type: web
    name: your-service-name
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app --bind 0.0.0.0:5000"
    envVars:
      - key: DATABASE_URL
        value: postgresql://user:password@db:5432/mydatabase