"""モデルを変更した説明

Revision ID: 733b83901703
Revises: edc097974df6
Create Date: 2025-01-04 15:54:06.256653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733b83901703'
down_revision = 'edc097974df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choices', sa.String(length=1024), nullable=True),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('passage')
    # ### end Alembic commands ###
