"""Initial migration

Revision ID: aa70701dcf04
Revises: f943566b8190
Create Date: 2025-01-01 18:31:34.674693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa70701dcf04'
down_revision = 'f943566b8190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
