"""Add question_type and explanation to Test model

Revision ID: edc097974df6
Revises: f7274af20810
Create Date: 2025-01-04 10:14:08.567030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc097974df6'
down_revision = 'f7274af20810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.alter_column('choices',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               nullable=True)
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('choices',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('explanation')
        batch_op.drop_column('text')
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
